"""Initial migration

Revision ID: 80106a4fec72
Revises: 
Create Date: 2024-11-08 01:44:56.535397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80106a4fec72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lista')
    # ### end Alembic commands ###
